### ISSUE TITLE
Feature request: dynamic menu bar icon

### ISSUE THREAD

**Issue by oscu0** [ZhiaDev/mac-proxy-manager#4]
Minor feature request: make a dynamic menu bar icon that is grey (and maybe has the switch in the off position) when no proxy is active. Something like this:
<img width="77" alt="image" src="https://github.com/ZhiaDev/mac-proxy-manager/assets/5638404/91d97507-6055-4f29-9015-006cfe36768b">
<img width="77" alt="image" src="https://github.com/ZhiaDev/mac-proxy-manager/assets/5638404/b157e1be-aeb3-413b-b9dc-d008c34942fb">

I can make the icon for you if it helps.

**Comment by ZhiaDev** [comment]
Hi @oscu0,

Thank you for the great idea you've shared. However, I regret to inform you that since this application is developed using the Flutter framework, it doesn't have easy access to native operating system features, making this task not easily achievable. Nonetheless, I will try to implement it in the future for sure.

By the way, here's some exciting news: I've just released a new version of the application which includes the feature of bypass list. You can download it through the [release](https://github.com/ZhiaDev/mac-proxy-manager/releases) page.

Cheers,
Zhia
